# Generated by Django 4.2.29 on 2026-03-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("language_code", models.CharField(default="urh", max_length=10)),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon_name", models.CharField(blank=True, max_length=50)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urhobo_text", models.CharField(max_length=300)),
                ("english_text", models.CharField(max_length=300)),
                ("pronunciation_guide", models.CharField(blank=True, max_length=300)),
                ("audio_url", models.URLField(blank=True)),
                ("example_usage", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, max_length=50)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "urhobo_text"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon_name", models.CharField(blank=True, max_length=50)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                ("estimated_minutes", models.PositiveIntegerField(default=5)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="curriculum.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("unit", "order")},
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("word", "Word"),
                            ("phrase", "Phrase"),
                            ("audio", "Audio"),
                            ("tip", "Tip"),
                        ],
                        max_length=10,
                    ),
                ),
                ("urhobo_text", models.CharField(max_length=500)),
                ("english_text", models.CharField(max_length=500)),
                ("pronunciation_guide", models.CharField(blank=True, max_length=500)),
                ("audio_url", models.URLField(blank=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="curriculum.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_vocabulary",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "vocabulary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_links",
                        to="curriculum.vocabularyitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("lesson", "vocabulary_item")},
            },
        ),
    ]
