# Generated by Django 4.2.29 on 2026-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessonattempt",
            index=models.Index(
                fields=["user", "lesson"], name="attempt_user_lesson_idx"
            ),
        ),
    ]
