# Generated by Django 4.2.29 on 2026-03-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("translation", "Choose Correct Translation"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "correct_answer_text",
                    models.CharField(
                        blank=True,
                        help_text="Used for fill_blank questions. Server validates against this.",
                        max_length=300,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "vocabulary_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="curriculum.vocabularyitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "side",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")], max_length=5
                    ),
                ),
                (
                    "pair_key",
                    models.PositiveIntegerField(
                        help_text="Items with matching pair_key on opposite sides are correct pairs."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_items",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "ordering": ["pair_key", "side"],
            },
        ),
    ]
